run_name: test

runner:
  threads: 32
  output_dir: ./output/browsergym_eval
  seed: 42

model_configs:
  gpt_4o:
    provider: openai 
    name: gpt-4o
    temperature: 0.6
  claude:
    provider: anthropic 
    name: claude-sonnet-4-20250514
    temperature: 0.6

benchmarks:
  webarena_mini:
    dataset: webarena-mini
    max_examples: -1
    max_steps: 10
    headless: true
    reset_env: false
    # viewport_size:
    #   width: 500
    #   height: 320

agents:
  unified_v2_gpt_4o:
    name: unified_v2
    model_config_name: gpt_4o
