run_name: test

runner:
  threads: 4
  output_dir: ./output/browsergym_eval
  seed: 42

model_configs:
  gpt_4.1:
    provider: openai 
    name: gpt-4.1
    temperature: 0.3
    max_tokens: 16384
  claude:
    provider: anthropic 
    name: claude-sonnet-4-20250514
    temperature: 0.3
    max_tokens: 8192
  claude_3_7_sonnet:
    provider: anthropic 
    name: claude-3-7-sonnet-20250219
    temperature: 0.3
    max_tokens: 8192

benchmarks:
  webarena_reddit:
    dataset: webarena-shopping-full
    max_examples: -1
    max_steps: 30
    headless: true
    reset_env: false
    # viewport_size:
    #   width: 500
    #   height: 320

agents:
  hsm_v3_claude:
    name: hsm_v3
    model_config_name: claude
