run_name: test

runner:
  threads: 8
  output_dirs:
    - ./output/browsergym_eval
    - ./results/online_mind2web
  seed: 42

model_configs:
  gpt_4.1:
    provider: openai 
    name: gpt-4.1
    temperature: 0.3
    max_tokens: 16384
  claude:
    provider: anthropic 
    name: claude-sonnet-4-20250514
    temperature: 0.3
    max_tokens: 8192
  claude_3_7_sonnet:
    provider: anthropic 
    name: claude-3-7-sonnet-20250219
    temperature: 0.3
    max_tokens: 8192

benchmarks:
  webarena_reddit:
    dataset: onlinem2w
    max_examples: -1
    max_steps: 15
    headless: true
    reset_env: false
    # viewport_size:
    #   width: 500
    #   height: 320

agents:
  # asi_gpt:
  #   name: asi
  #   model_config_name: gpt_4.1
  #   action_file_path: /root/digital-agent/orby/digitalagent/actions/asi/gpt-4.1-backups/shopping_step_180_20250624_205426.py
  hsm_v3_gpt:
    name: hsm_v3
    model_config_name: gpt_4.1
  # gpt:
  #   name: asi
  #   model_config_name: gpt_4.1
  #   action_file_path: /root/digital-agent/orby/digitalagent/actions/asi/empty.py
  # asi_gpt:
  #   name: asi
  #   model_config_name: gpt_4.1
  #   action_file_path: /root/digital-agent/orby/digitalagent/actions/asi/gpt-4.1-backups/shopping_step_180_20250624_205426.py
  # asi_gpt_2:
  #   name: asi
  #   model_config_name: gpt_4.1
  #   action_file_path: /root/digital-agent/orby/digitalagent/actions/asi/gpt-4.1-backups/shopping_step_160_20250624_200110.py
  # asi_gpt_3:
  #   name: asi
  #   model_config_name: gpt_4.1
  #   action_file_path: /root/digital-agent/orby/digitalagent/actions/asi/gpt-4.1-backups/shopping_step_120_20250624_185946.py
  # asi_gpt_4:
  #   name: asi
  #   model_config_name: gpt_4.1
  #   action_file_path: /root/digital-agent/orby/digitalagent/actions/asi/gpt-4.1-backups/shopping_step_80_20250624_175151.py
  # asi_gpt_5:
  #   name: asi
  #   model_config_name: gpt_4.1
  #   action_file_path: /root/digital-agent/orby/digitalagent/actions/asi/gpt-4.1-backups/shopping_step_40_20250624_161813.py
  # asi_gpt_6:
  #   name: asi
  #   model_config_name: gpt_4.1
  #   action_file_path: /root/digital-agent/orby/digitalagent/actions/asi/gpt-4.1-backups/shopping_step_20_20250624_153924.py
  # hsm_v3_gpt:
  #   name: hsm_v3
  #   model_config_name: gpt_4.1
  # asi_claude:
  #   name: asi
  #   model_config_name: claude
  # hsm_v3_claude:
  #   name: hsm_v3
  #   model_config_name: claude

