run_name: test

runner:
  threads: 1
  output_dir: ./output/browsergym_eval
  seed: 17
  timeout_secs: 600

model_configs:
  claude:
    provider: anthropic 
    name: claude-3-7-sonnet-20250219
    temperature: 0

agents:
  sva_v3:
    name: sva_v3
    model_config_name: claude

benchmarks:
  subtaskbench:
    dataset: webarena-easy
    max_examples: 10
    max_steps: 20
    headless: true
    reset_env: false
    viewport_size:
      width: 1280
      height: 860 # 720 original recorded height + 40 debugger banner height + 100 b/c somehow the height is at 620 when 760 is set here
    example_ids:
    # Working and vetted online tasks
    - "browsergym/subtaskbench.online.0"
    - "browsergym/subtaskbench.online.1"
    - "browsergym/subtaskbench.online.2"
    # - "browsergym/subtaskbench.online.3" # env is fine but scrolling doesnt work in browsergym
    - "browsergym/subtaskbench.online.4"
    - "browsergym/subtaskbench.online.5" 
    - "browsergym/subtaskbench.online.6"
    - "browsergym/subtaskbench.online.7"
    - "browsergym/subtaskbench.online.8"
    - "browsergym/subtaskbench.online.9"
    - "browsergym/subtaskbench.online.10"
    - "browsergym/subtaskbench.online.11"
    - "browsergym/subtaskbench.online.12"
    - "browsergym/subtaskbench.online.13"
    - "browsergym/subtaskbench.online.14"
    - "browsergym/subtaskbench.online.15"
    # - "browsergym/subtaskbench.online.16"  # eval condition needs to be verified
    - "browsergym/subtaskbench.online.17" 
    - "browsergym/subtaskbench.online.18"
    # - "browsergym/subtaskbench.online.19"
    - "browsergym/subtaskbench.online.20"
    - "browsergym/subtaskbench.online.21"
    # - "browsergym/subtaskbench.online.22"
    - "browsergym/subtaskbench.online.23"
    - "browsergym/subtaskbench.online.24"
    - "browsergym/subtaskbench.online.25"
    - "browsergym/subtaskbench.online.26"
    # - "browsergym/subtaskbench.online.27" # eval condition needs to be verified
    - "browsergym/subtaskbench.online.28"
    # - "browsergym/subtaskbench.online.29" # eval environment is broken
    - "browsergym/subtaskbench.online.30"
    - "browsergym/subtaskbench.online.31"
    - "browsergym/subtaskbench.online.32"
    # - "browsergym/subtaskbench.online.33" # env is fine but action space is not supported
    - "browsergym/subtaskbench.online.34"
    - "browsergym/subtaskbench.online.35"
    - "browsergym/subtaskbench.online.36"
    # - "browsergym/subtaskbench.online.37"
    - "browsergym/subtaskbench.online.38"
    - "browsergym/subtaskbench.online.39"
    - "browsergym/subtaskbench.online.40"
    - "browsergym/subtaskbench.online.41"
    # - "browsergym/subtaskbench.online.42" # eval needs to be verified
    # - "browsergym/subtaskbench.online.43" # eval needs rerecording
    - "browsergym/subtaskbench.online.44"
    - "browsergym/subtaskbench.online.45"
    # - "browsergym/subtaskbench.online.46" # eval condition needs to be verified
    - "browsergym/subtaskbench.online.47"
    # - "browsergym/subtaskbench.online.48" # eval needs rerecording
    # - "browsergym/subtaskbench.online.49" # env crashes
    # - "browsergym/subtaskbench.online.50" # eval fails, needs checking
    # - "browsergym/subtaskbench.online.51" # eval fails, needs checking
    # - "browsergym/subtaskbench.online.52" # eval fails, needs checking
    # - "browsergym/subtaskbench.online.53" # eval fails, needs checking
    # - "browsergym/subtaskbench.online.54" # eval fails, needs checking
    - "browsergym/subtaskbench.online.55"
    - "browsergym/subtaskbench.online.56"
    - "browsergym/subtaskbench.online.57"
    - "browsergym/subtaskbench.online.58"
    - "browsergym/subtaskbench.online.59"
    - "browsergym/subtaskbench.online.60"
    # - "browsergym/subtaskbench.online.61" # system dropdown
    - "browsergym/subtaskbench.online.62"
    - "browsergym/subtaskbench.online.63"
    # - "browsergym/subtaskbench.online.64" # system dropdown
    - "browsergym/subtaskbench.online.65"
    # - "browsergym/subtaskbench.online.66" # system dropdown
    - "browsergym/subtaskbench.online.67"
    # - "browsergym/subtaskbench.online.68" # system dropdown
    # - "browsergym/subtaskbench.online.69" # system dropdown
    # - "browsergym/subtaskbench.online.70" # system dropdown 
    # - "browsergym/subtaskbench.online.71" # system dropdown
    - "browsergym/subtaskbench.online.72"
    - "browsergym/subtaskbench.online.73"
    - "browsergym/subtaskbench.online.74"
    - "browsergym/subtaskbench.online.75"
    # - "browsergym/subtaskbench.online.76" # goal needs to be redefined according to timestamp
    # - "browsergym/subtaskbench.online.77" # goal needs to be redefined according to timestamp
    # - "browsergym/subtaskbench.online.78" # goal needs to be redefined according to timestamp
    - "browsergym/subtaskbench.online.79"
    - "browsergym/subtaskbench.online.80"
    - "browsergym/subtaskbench.online.81"
    - "browsergym/subtaskbench.online.82"
    - "browsergym/subtaskbench.online.83"
    - "browsergym/subtaskbench.online.84"
    - "browsergym/subtaskbench.online.85"
    - "browsergym/subtaskbench.online.86"
    - "browsergym/subtaskbench.online.87"
